// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#define KERNELTOY_DEVICE_TYPE 0x8115

typedef enum _KERNELTOY_HAL_INFORMATION_CLASS {
    KrtHalPlatformTimerInformationV1,
} KERNELTOY_HAL_INFORMATION_CLASS;

typedef struct _KERNELTOY_HAL_PLATFORM_TIMER_INFORMATION_V1 {
    ULONG ClockInterruptSource;
    ULONG PerformanceCounterSource;
} KERNELTOY_HAL_PLATFORM_TIMER_INFORMATION_V1, * PKERNELTOY_HAL_PLATFORM_TIMER_INFORMATION_V1;

typedef struct _KERNELTOY_HAL_INFORMATION_REQUEST {
    KERNELTOY_HAL_INFORMATION_CLASS HalInformationClass;
} KERNELTOY_HAL_INFORMATION_REQUEST, * PKERNELTOY_HAL_INFORMATION_REQUEST;

#define IOCTL_KERNELTOY_QUERY_HAL_INFORMATION \
    CTL_CODE(KERNELTOY_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)
